        /*/index.html 200```
    *   **For `netlify.toml`:** Add the following tothe `netlify.toml` file:```toml
        [[redirects]]
          from = "/*"
          to = "/index.html"
status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"